### ISSUE TITLE
Erreur 500 après compilation config

### ISSUE THREAD

**Issue by Philippe-M** [alchemy-fr/Phraseanet#1998]
Avec la VM de la 4.0 preview mise à jour le 25/10/2016 à 16h40.

Tout est ok après update. Je modifie le fichier config/configuration.yml, je change les paramètres 

```
            type: Checker\Sha256
            enabled: false

            type: Checker\UUID
            enabled: false

            type: Checker\Filename
            enabled: true
            options:
                sensitive: false
```

 je compile la configuration 

`bin/console compile:configuration`

J'obtiens une erreur 500 dans mon navigateur pour accéder à la page prod/. La page admin/ reste accessible.

Je rétablie la configuration par défaut, je re-compile, ça marche à nouveau. Je tente cette config

```
            type: Checker\Sha256
            enabled: true

            type: Checker\UUID
            enabled: true

            type: Checker\Filename
            enabled: true
            options:
                sensitive: false
```

Je compile est c'est ok plus d'erreur 500.

Donc c'est lorsque le `Checker\Filename`est activé seul alors l'erreur 500 apparait.

J'ai réalisé le même test avec la version 388 et tout est ok.
