### ISSUE TITLE
Geolocation not working - "MapBox require an access token" despite having one

### ISSUE THREAD

**Issue by LizardWithHat** [alchemy-fr/Phraseanet#3625]
I have a Phraseanet Installation via Docker and provided the installation a Mapbox Public Token in it's configuration, however neither does Geolocation nor Geolocation Search work.
The Javascript Console just complains about not having an access token.

```
Uncaught Error: MapBox require an access token
    initializeMap http://phraseanet.planersocietaet.local:8082/assets/production/production.min.js:3364
    appendMapContent http://phraseanet.planersocietaet.local:8082/assets/production/production.min.js:3358
    onModalReady http://phraseanet.planersocietaet.local:8082/assets/production/production.min.js:64212
    openModal http://phraseanet.planersocietaet.local:8082/assets/production/production.min.js:64192
    initialize http://phraseanet.planersocietaet.local:8082/assets/production/production.min.js:63370
    jQuery 2
production.min.js:3364:19
```
These are the relevant (anonymized) config rows:
```
geocoding-providers:
    -
        map-provider: mapboxWebGL
        enabled: false
        public-key: 'pk.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        map-layers:
            -
```
The config file gets read and compiles correctly as far as I know and I followed the online 4.1 configuration documentation.
